### ISSUE TITLE
def assemble_mentors_dict(self, cursor)

### ISSUE THREAD

**Issue by A-Lazar-A** [Mentor-Whirlpool/mentor_whirlpool#1]
Что будет если у ментора еще нет студентов? Вероятно эта ошибка
'NoneType' object is not iterable
`line = {
                'id': i[0],
                'name': i[1],
                'chat_id': i[2],
                'subjects': i[3],
                'load': i[4],
                'students': [await self.get_students(student=id)[0] for id in i[5]],
            }`
@zinstack625

**Comment by zinstack625** [comment]
Разрешено в 5b70a9ecba9a3f160c83ac2bb082debf2d8f0654
