### ISSUE TITLE
Mentors enhancements

### ISSUE THREAD

**Issue by A-Lazar-A** [Mentor-Whirlpool/mentor_whirlpool#2]
1)get_subjects - добавить фильтр для ментора чтоб возвращало темы определенного ментора
2)assemble_courses_dict - "student" возвращать не айди а сущность студента из бд
3)get_course_works - добавить фильтр по id (не chat_id) т.е. возвращает одну курсовую по айдишнику
4)  
```
subjects_to_add = await db.get_subjects()

for subject in subjects_to_add:
    if subject in my_subjects_:
        subjects_to_add.remove(subject)
```
мне просто не нравится этот кусок кода но как заменить хз

@zinstack625

**Comment by zinstack625** [comment]
1. Темы определённого ментора лучше доставать из `get_mentors()`
2. Посмотрим что можно делать после реворка на реляции
3. Сделано в 10c366275ee0e8d47adaa64252ed476188aba929
4. Могу предложить
`subjects_to_add = [subj for subj in await db.get_subjects() if not in my_subjects_]`

На данный момент нужно сделать отношения в БД, посмотрим что из этого получится, но мне в это ещё раз нужно вчитаться

**Comment by zinstack625** [comment]
1. Темы ментора теперь можно доставать при помощи `get_subjects()` с аргументом `mentor_id`
2. Увы и ах, ничего не могу поделать. Возникает циклическая зависимость и всё подвисает
