### ISSUE TITLE
accept_work

### ISSUE THREAD

**Issue by A-Lazar-A** [Mentor-Whirlpool/mentor_whirlpool#4]
```
await self.db.execute('UPDATE MENTORS SET LOAD = LOAD + 1, '
                              'STUDENTS = ARRAY_APPEND(STUDENTS, CAST(%S AS BIGINT))'
                              'WHERE ID = %s', (line[1], mentor_id,))
```
`CAST(%S AS BIGINT)`
only '%s', '%b', '%t' are allowed as placeholders, got '%S'

**Comment by zinstack625** [comment]
Исправлено где-то [тут](https://github.com/Mentor-Whirlpool/mentor_whirlpool/commit/a05facf926b34c59462557f7c1ccf9b4d93ef41f#diff-8648b652b4a36dcf69abfe487e354fc88c71b2c916631af8f367f63e8d626c54R303)
