### ISSUE TITLE
Рефактор файлов

### ISSUE THREAD

**Issue by A-Lazar-A** [Mentor-Whirlpool/mentor_whirlpool#76]
Разделение файлов на папки с модулями
```
└── mentors
    ├── my_students.py
    ├── my_subjects.py
    └── works.py
```

**Comment by A-Lazar-A** [comment]
Наброски [тут](https://github.com/Mentor-Whirlpool/mentor_whirlpool/tree/refactor_files_structure)

**Comment by zinstack625** [comment]
Разрешено в https://github.com/Mentor-Whirlpool/mentor_whirlpool/pull/82
